# -*- coding: utf-8 -*-

# mainWidget implementation generated from reading ui file 'D:\Desktop\UI\MainFrame\QtGUI\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui

from QNavigationWidget import QNavigationWidget


class Ui_Form(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.windowSize = (1600, 800)
        self.navigationRowHeight = 50
        self.navigationWidth = 200

        self.setFixedSize(*self.windowSize)

        self.mainWidget = QtWidgets.QWidget()
        self.navigationWidget = QNavigationWidget(self.mainWidget)  # Left Widget
        self.rightWidget = QtWidgets.QWidget(self.mainWidget)  # Right Widget

        self.rightLayout = QtWidgets.QHBoxLayout(self.rightWidget)
        self.mainLayout = QtWidgets.QHBoxLayout(self.mainWidget)

        self.tipsLabel = QtWidgets.QLabel("Item: 0")
        pass

    def slot_func(self, idx):
        self.tipsLabel.setText(f"Item: {idx}")
        # self.mainLayout.itemAt(1).widget().close()
        pass

    def setupUi(self):
        self.navigationWidget.setRowHeight(self.navigationRowHeight)
        self.navigationWidget.addItem("常 规")
        self.navigationWidget.addItem("画 面")
        self.navigationWidget.addItem("字 幕")
        self.navigationWidget.addItem("下 载")
        self.navigationWidget.addItem("其 他")
        self.navigationWidget.addItem("关 于")
        self.navigationWidget.setFixedWidth(self.navigationWidth)

        self.rightWidget.setFixedWidth(self.width() - self.navigationWidget.width())

        # self.rightLayout.addWidget(self.tipsLabel)
        self.rightLayout.addWidget(self.tipsLabel, 0, QtCore.Qt.AlignCenter)

        self.mainWidget.setObjectName("mainWidget")

        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.addWidget(self.navigationWidget)
        self.mainLayout.addWidget(self.rightWidget)

        self.setCentralWidget(self.mainWidget)
        self.navigationWidget.signal.connect(self.slot_func)

        QtCore.QMetaObject.connectSlotsByName(self.mainWidget)
        pass


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_Form()
    ui.setupUi()

    ui.show()

    sys.exit(app.exec_())
    pass
